import streamlit as st
import pandas as pd
import requests
import time
from datetime import datetime, timedelta
import numpy as np
from functools import lru_cache

# Configure page
st.set_page_config(page_title="Advanced Stock Screener with Technical Indicators", layout="wide")

# Custom CSS
st.markdown("""
<style>
.stock-table {
    border-radius: 10px;
    margin: 10px 0;
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
}
.positive { color: green; }
.negative { color: red; }
.small-table { font-size: 0.8rem; }
.metric-card {
    background: #f0f2f6;
    padding: 10px;
    border-radius: 5px;
    margin: 5px 0;
}
</style>
""", unsafe_allow_html=True)

# Example stock list - replace with your full 2000 stocks
EXAMPLE_STOCKS = [
    '20MICRONS.NS', '21STCENMGM.NS', '360ONE.NS', '3IINFOLTD.NS', '3MINDIA.NS', '3PLAND.NS', '5PAISA.NS', '63MOONS.NS', 'A2ZINFRA.NS', 'AAATECH.NS', 'AADHARHFC.NS', 'AAKASH.NS', 'AAREYDRUGS.NS', 'AARON.NS', 'AARTECH.NS', 'AARTIDRUGS.NS', 'AARTIIND.NS', 'AARTIPHARM.NS', 'AARTISURF.NS', 'AARVEEDEN.NS', 'AARVI.NS', 'AAVAS.NS', 'ABAN.NS', 'ABB.NS', 'ABBOTINDIA.NS', 'ABCAPITAL.NS', 'ABDL.NS', 'ABFRL.NS', 'ABINFRA.NS', 'ABLBL.NS', 'ABMINTLLTD.NS', 'ABREL.NS', 'ABSLAMC.NS', 'ACC.NS', 'ACCELYA.NS', 'ACCURACY.NS', 'ACE.NS', 'ACEINTEG.NS', 'ACI.NS', 'ACL.NS', 'ACLGATI.NS', 'ACMESOLAR.NS', 'ACUTAAS.NS', 'ADANIENSOL.NS', 'ADANIENT.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'ADFFOODS.NS', 'ADL.NS', 'ADOR.NS', 'ADROITINFO.NS', 'ADSL.NS', 'ADVANIHOTR.NS', 'ADVENZYMES.NS', 'AEGISLOG.NS', 'AEGISVOPAK.NS', 'AEROENTER.NS', 'AEROFLEX.NS', 'AETHER.NS', 'AFCONS.NS', 'AFFLE.NS', 'AFFORDABLE.NS', 'AFIL.NS', 'AFSL.NS', 'AGARIND.NS', 'AGARWALEYE.NS', 'AGI.NS', 'AGIIL.NS', 'AGRITECH.NS', 'AGROPHOS.NS', 'AGSTRA.NS', 'AHLADA.NS', 'AHLEAST.NS', 'AHLUCONT.NS', 'AIAENG.NS', 'AIIL.NS', 'AIRAN.NS', 'AIROLAM.NS', 'AJANTPHARM.NS', 'AJAXENGG.NS', 'AJMERA.NS', 'AJOONI.NS', 'AKASH.NS', 'AKG.NS', 'AKI.NS', 'AKSHAR.NS', 'AKSHARCHEM.NS', 'AKSHOPTFBR.NS', 'AKUMS.NS', 'AKZOINDIA.NS', 'ALANKIT.NS', 'ALBERTDAVD.NS', 'ALEMBICLTD.NS', 'ALICON.NS', 'ALIVUS.NS', 'ALKALI.NS', 'ALKEM.NS', 'ALKYLAMINE.NS', 'ALLCARGO.NS', 'ALLDIGI.NS', 'ALMONDZ.NS', 'ALOKINDS.NS', 'ALPA.NS', 'ALPHAGEO.NS', 'AMBER.NS', 'AMBICAAGAR.NS', 'AMBIKCO.NS', 'AMBUJACEM.NS', 'AMDIND.NS', 'AMJLAND.NS', 'AMNPLST.NS', 'AMRUTANJAN.NS', 'ANANDRATHI.NS', 'ANANTRAJ.NS', 'ANDHRAPAP.NS', 'ANDHRSUGAR.NS', 'ANGELONE.NS', 'ANIKINDS.NS', 'ANKITMETAL.NS', 'ANMOL.NS', 'ANSALAPI.NS', 'ANTGRAPHIC.NS', 'ANUHPHR.NS', 'ANUP.NS', 'ANURAS.NS', 'APARINDS.NS', 'APCL.NS', 'APCOTEXIND.NS', 'APEX.NS', 'APLAPOLLO.NS', 'APLLTD.NS', 'APOLLO.NS', 'APOLLOHOSP.NS', 'APOLLOPIPE.NS', 'APOLLOTYRE.NS', 'APOLSINHOT.NS', 'APTECHT.NS', 'APTUS.NS', 'ARCHIDPLY.NS', 'ARCHIES.NS', 'ARE&M.NS', 'ARENTERP.NS', 'ARIES.NS', 'ARIHANTCAP.NS', 'ARIHANTSUP.NS', 'ARISINFRA.NS', 'ARKADE.NS', 'ARMANFIN.NS', 'AROGRANITE.NS', 'ARROWGREEN.NS', 'ARSHIYA.NS', 'ARSSINFRA.NS', 'ARTEMISMED.NS', 'ARTNIRMAN.NS', 'ARVEE.NS', 'ARVIND.NS', 'ARVINDFASN.NS', 'ARVSMART.NS', 'ASAHIINDIA.NS', 'ASAHISONG.NS', 'ASAL.NS', 'ASALCBR.NS', 'ASHAPURMIN.NS', 'ASHIANA.NS', 'ASHIMASYN.NS', 'ASHOKA.NS', 'ASHOKAMET.NS', 'ASHOKLEY.NS', 'ASIANENE.NS', 'ASIANHOTNR.NS', 'ASIANPAINT.NS', 'ASIANTILES.NS', 'ASKAUTOLTD.NS', 'ASMS.NS', 'ASPINWALL.NS', 'ASTEC.NS', 'ASTEC-RE.NS', 'ASTERDM.NS', 'ASTRAL.NS', 'ASTRAMICRO.NS', 'ASTRAZEN.NS', 'ASTRON.NS', 'ATALREAL.NS', 'ATAM.NS', 'ATGL.NS', 'ATHERENERG.NS', 'ATL.NS', 'ATLANTAA.NS', 'ATLASCYCLE.NS', 'ATUL.NS', 'ATULAUTO.NS', 'AUBANK.NS', 'AURIONPRO.NS', 'AUROPHARMA.NS', 'AURUM.NS', 'AUSOMENT.NS', 'AUTOAXLES.NS', 'AUTOIND.NS', 'AVADHSUGAR.NS', 'AVALON.NS', 'AVANTEL.NS', 'AVANTIFEED.NS', 'AVG.NS', 'AVL.NS', 'AVONMORE.NS', 'AVROIND.NS', 'AVTNPL.NS', 'AWFIS.NS', 'AWHCL.NS', 'AWL.NS', 'AXISBANK.NS', 'AXISCADES.NS', 'AXITA.NS', 'AYMSYNTEX.NS', 'AZAD.NS', 'BAFNAPH.NS', 'BAGFILMS.NS', 'BAIDFIN.NS', 'BAJAJ-AUTO.NS', 'BAJAJCON.NS', 'BAJAJELEC.NS', 'BAJAJFINSV.NS', 'BAJAJHCARE.NS', 'BAJAJHFL.NS', 'BAJAJHIND.NS', 'BAJAJHLDNG.NS', 'BAJAJINDEF.NS', 'BAJEL.NS', 'BAJFINANCE.NS', 'BALAJEE.NS', 'BALAJITELE.NS', 'BALAMINES.NS', 'BALAXI.NS', 'BALKRISHNA.NS', 'BALKRISIND.NS', 'BALMLAWRIE.NS', 'BALPHARMA.NS', 'BALRAMCHIN.NS', 'BALUFORGE.NS', 'BANARBEADS.NS', 'BANARISUG.NS', 'BANCOINDIA.NS', 'BANDHANBNK.NS', 'BANG.NS', 'BANKA.NS', 'BANKBARODA.NS', 'BANKINDIA.NS', 'BANSALWIRE.NS', 'BANSWRAS.NS', 'BARBEQUE.NS', 'BASF.NS', 'BASML.NS', 'BATAINDIA.NS', 'BAYERCROP.NS', 'BBL.NS', 'BBOX.NS', 'BBTC.NS', 'BBTCL.NS', 'BCG.NS', 'BCLIND.NS', 'BCONCEPTS.NS', 'BDL.NS', 'BEARDSELL.NS', 'BECTORFOOD.NS', 'BEDMUTHA.NS', 'BEL.NS', 'BELRISE.NS', 'BEML.NS', 'BEPL.NS', 'BERGEPAINT.NS', 'BESTAGRO.NS', 'BFINVEST.NS', 'BFUTILITIE.NS', 'BGRENERGY.NS', 'BHAGCHEM.NS', 'BHAGERIA.NS', 'BHAGYANGR.NS', 'BHANDARI.NS', 'BHARATFORG.NS', 'BHARATGEAR.NS', 'BHARATRAS.NS', 'BHARATSE.NS', 'BHARATWIRE.NS', 'BHARTIARTL.NS', 'BHARTIHEXA.NS', 'BHEL.NS', 'BIGBLOC.NS', 'BIKAJI.NS', 'BIL.NS', 'BILVYAPAR.NS', 'BIOCON.NS', 'BIOFILCHEM.NS', 'BIRLACABLE.NS', 'BIRLACORPN.NS', 'BIRLAMONEY.NS', 'BIRLANU.NS', 'BLACKBUCK.NS', 'BLAL.NS', 'BLBLIMITED.NS', 'BLISSGVS.NS', 'BLKASHYAP.NS', 'BLS.NS', 'BLSE.NS', 'BLUECOAST.NS', 'BLUEDART.NS', 'BLUEJET.NS', 'BLUESTARCO.NS', 'BLUSPRING.NS', 'BODALCHEM.NS', 'BOHRAIND.NS', 'BOMDYEING.NS', 'BORANA.NS', 'BOROLTD.NS', 'BORORENEW.NS', 'BOROSCI.NS', 'BOSCHLTD.NS', 'BPCL.NS', 'BPL.NS', 'BRIGADE.NS', 'BRITANNIA.NS', 'BRNL.NS', 'BROOKS.NS', 'BSE.NS', 'BSHSL.NS', 'BSL.NS', 'BSOFT.NS', 'BTML.NS', 'BUTTERFLY.NS', 'BVCL.NS', 'BYKE.NS', 'CALSOFT.NS', 'CAMLINFINE.NS', 'CAMPUS.NS', 'CAMS.NS', 'CANBK.NS', 'CANFINHOME.NS', 'CANTABIL.NS', 'CAPACITE.NS', 'CAPITALSFB.NS', 'CAPLIPOINT.NS', 'CAPTRU-RE.NS', 'CAPTRUST.NS', 'CARBORUNIV.NS', 'CARERATING.NS', 'CARRARO.NS', 'CARTRADE.NS', 'CARYSIL.NS', 'CASTROLIND.NS', 'CCCL.NS', 'CCHHL.NS', 'CCL.NS', 'CDSL.NS', 'CEATLTD.NS', 'CEIGALL.NS', 'CELEBRITY.NS', 'CELLO.NS', 'CENTENKA.NS', 'CENTEXT.NS', 'CENTRALBK.NS', 'CENTRUM.NS', 'CENTUM.NS', 'CENTURYPLY.NS', 'CERA.NS', 'CEREBRAINT.NS', 'CESC.NS', 'CEWATER.NS', 'CGCL.NS', 'CGPOWER.NS', 'CHALET.NS', 'CHAMBLFERT.NS', 'CHEMBOND.NS', 'CHEMCON.NS', 'CHEMFAB.NS', 'CHEMPLASTS.NS', 'CHENNPETRO.NS', 'CHEVIOT.NS', 'CHOICEIN.NS', 'CHOLAFIN.NS', 'CHOLAHLDNG.NS', 'CIEINDIA.NS', 'CIFL.NS', 'CIGNITITEC.NS', 'CINELINE.NS', 'CINEVISTA.NS', 'CIPLA.NS', 'CLEAN.NS', 'CLEDUCATE.NS', 'CLSEL.NS', 'CMSINFO.NS', 'COALINDIA.NS', 'COASTCORP.NS', 'COCHINSHIP.NS', 'COFFEEDAY.NS', 'COFORGE.NS', 'COHANCE.NS', 'COLPAL.NS', 'COMPINFO.NS', 'COMPUSOFT.NS', 'COMSYN.NS', 'CONCOR.NS', 'CONCORDBIO.NS', 'CONFIPET.NS', 'CONSOFINVT.NS', 'CONTROLPR.NS', 'CORALFINAC.NS', 'CORDSCABLE.NS', 'COROMANDEL.NS', 'COSMOFIRST.NS', 'COUNCODOS.NS', 'CPCAP.NS', 'CRAFTSMAN.NS', 'CREATIVE.NS', 'CREATIVEYE.NS', 'CREDITACC.NS', 'CREST.NS', 'CRISIL.NS', 'CRIZAC.NS', 'CROMPTON.NS', 'CROWN.NS', 'CSBBANK.NS', 'CSLFINANCE.NS', 'CTE.NS', 'CUB.NS', 'CUBEXTUB.NS', 'CUMMINSIND.NS', 'CUPID.NS', 'CURAA.NS', 'CYBERMEDIA.NS', 'CYBERTECH.NS', 'CYIENT.NS', 'CYIENTDLM.NS', 'DABUR.NS', 'DALBHARAT.NS', 'DALMIASUG.NS', 'DAMCAPITAL.NS', 'DAMODARIND.NS', 'DANGEE.NS', 'DATAMATICS.NS', 'DATAPATTNS.NS', 'DAVANGERE.NS', 'DBCORP.NS', 'DBEIL.NS', 'DBL.NS', 'DBOL.NS', 'DBREALTY.NS', 'DBSTOCKBRO.NS', 'DCAL.NS', 'DCBBANK.NS', 'DCI.NS', 'DCM.NS', 'DCMFINSERV.NS', 'DCMNVL.NS', 'DCMSHRIRAM.NS', 'DCMSRIND.NS', 'DCW.NS', 'DCXINDIA.NS', 'DDEVPLSTIK.NS', 'DECCANCE.NS', 'DEEDEV.NS', 'DEEPAKFERT.NS', 'DEEPAKNTR.NS', 'DEEPINDS.NS', 'DELHIVERY.NS', 'DELPHIFX.NS', 'DELTACORP.NS', 'DELTAMAGNT.NS', 'DEN.NS', 'DENORA.NS', 'DENTA.NS', 'DEVIT.NS', 'DEVYANI.NS', 'DGCONTENT.NS', 'DHAMPURSUG.NS', 'DHANBANK.NS', 'DHANI.NS', 'DHANUKA.NS', 'DHARAN.NS', 'DHARMAJ.NS', 'DHRUV.NS', 'DHUNINV.NS', 'DIACABS.NS', 'DIAMINESQ.NS', 'DIAMONDYD.NS', 'DICIND.NS', 'DIFFNKG.NS', 'DIGIDRIVE.NS', 'DIGISPICE.NS', 'DIGITIDE.NS', 'DIGJAMLMTD.NS', 'DIL.NS', 'DISHTV.NS', 'DIVGIITTS.NS', 'DIVISLAB.NS', 'DIXON.NS', 'DJML.NS', 'DLF.NS', 'DLINKINDIA.NS', 'DMART.NS', 'DMCC.NS', 'DNAMEDIA.NS', 'DODLA.NS', 'DOLATALGO.NS', 'DOLLAR.NS', 'DOLPHIN.NS', 'DOMS.NS', 'DONEAR.NS', 'DPABHUSHAN.NS', 'DPSCLTD.NS', 'DPWIRES.NS', 'DRCSYSTEMS.NS', 'DREAMFOLKS.NS', 'DREDGECORP.NS', 'DRREDDY.NS', 'DSSL.NS', 'DTIL.NS', 'DUCON.NS', 'DVL.NS', 'DWARKESH.NS', 'DYCL.NS', 'DYNAMATECH.NS', 'DYNPRO.NS', 'E2E.NS', 'EASEMYTRIP.NS', 'ECLERX.NS', 'ECOSMOBLTY.NS', 'EDELWEISS.NS', 'EICHERMOT.NS', 'EIDPARRY.NS', 'EIEL.NS', 'EIFFL.NS', 'EIHAHOTELS.NS', 'EIHOTEL.NS', 'EIMCOELECO.NS', 'EKC.NS', 'ELDEHSG.NS', 'ELECON.NS', 'ELECTCAST.NS', 'ELECTHERM.NS', 'ELGIEQUIP.NS', 'ELGIRUBCO.NS', 'ELIN.NS', 'ELLEN.NS', 'EMAMILTD.NS', 'EMAMIPAP.NS', 'EMAMIREAL.NS', 'EMBDL.NS', 'EMCURE.NS', 'EMIL.NS', 'EMKAY.NS', 'EMMBI.NS', 'EMSLIMITED.NS', 'EMUDHRA.NS', 'ENDURANCE.NS', 'ENERGYDEV.NS', 'ENGINERSIN.NS', 'ENIL.NS', 'ENRIN.NS', 'ENTERO.NS', 'EPACK.NS', 'EPIGRAL.NS', 'EPL.NS', 'EQUIPPP.NS', 'EQUITASBNK.NS', 'ERIS.NS', 'ESABINDIA.NS', 'ESAFSFB.NS', 'ESCORTS.NS', 'ESSARSHPNG.NS', 'ESSENTIA.NS', 'ESTER.NS', 'ETERNAL.NS', 'ETHOSLTD.NS', 'EUREKAFORB.NS', 'EUROTEXIND.NS', 'EVEREADY.NS', 'EVERESTIND.NS', 'EXCEL.NS', 'EXCELINDUS.NS', 'EXICOM.NS', 'EXICOM-RE.NS', 'EXIDEIND.NS', 'EXPLEOSOL.NS', 'EXXARO.NS', 'FACT.NS', 'FAIRCHEMOR.NS', 'FAZE3Q.NS', 'FCL.NS', 'FCSSOFT.NS', 'FDC.NS', 'FEDERALBNK.NS', 'FEDFINA.NS', 'FEL.NS', 'FELDVR.NS', 'FIBERWEB.NS', 'FIEMIND.NS', 'FILATEX.NS', 'FILATFASH.NS', 'FINCABLES.NS', 'FINEORG.NS', 'FINOPB.NS', 'FINPIPE.NS', 'FIRSTCRY.NS', 'FISCHER.NS', 'FIVESTAR.NS', 'FLAIR.NS', 'FLEXITUFF.NS', 'FLUOROCHEM.NS', 'FMGOETZE.NS', 'FMNL.NS', 'FOCUS.NS', 'FOODSIN.NS', 'FORCEMOT.NS', 'FORTIS.NS', 'FOSECOIND.NS', 'FSL.NS', 'FUSION.NS', 'GABRIEL.NS', 'GAEL.NS', 'GAIL.NS', 'GALAPREC.NS', 'GALAXYSURF.NS', 'GALLANTT.NS', 'GANDHAR.NS', 'GANDHITUBE.NS', 'GANECOS.NS', 'GANESHBE.NS', 'GANESHHOUC.NS', 'GANGAFORGE.NS', 'GANGESSECU.NS', 'GARFIBRES.NS', 'GARUDA.NS', 'GATECH.NS', 'GATECHDVR.NS', 'GATEWAY.NS', 'GAYAHWS.NS', 'GAYAPROJ.NS', 'GEECEE.NS', 'GEEKAYWIRE.NS', 'GENCON.NS', 'GENESYS.NS', 'GENUSPAPER.NS', 'GENUSPOWER.NS', 'GEOJITFSL.NS', 'GEPIL.NS', 'GESHIP.NS', 'GFLLIMITED.NS', 'GHCL.NS', 'GHCLTEXTIL.NS', 'GICHSGFIN.NS', 'GICRE.NS', 'GILLANDERS.NS', 'GILLETTE.NS', 'GINNIFILA.NS', 'GIPCL.NS', 'GKWLIMITED.NS', 'GLAND.NS', 'GLAXO.NS', 'GLENMARK.NS', 'GLFL.NS', 'GLOBAL.NS', 'GLOBALE.NS', 'GLOBALVECT.NS', 'GLOBE.NS', 'GLOBECIVIL.NS', 'GLOBUSSPR.NS', 'GLOSTERLTD.NS', 'GMBREW.NS', 'GMDCLTD.NS', 'GMMPFAUDLR.NS', 'GMRAIRPORT.NS', 'GMRP&UI.NS', 'GNA.NS', 'GNFC.NS', 'GOACARBON.NS', 'GOCLCORP.NS', 'GOCOLORS.NS', 'GODAVARIB.NS', 'GODFRYPHLP.NS', 'GODHA.NS', 'GODIGIT.NS', 'GODREJAGRO.NS', 'GODREJCP.NS', 'GODREJIND.NS', 'GODREJPROP.NS', 'GOENKA.NS', 'GOKEX.NS', 'GOKUL.NS', 'GOKULAGRO.NS', 'GOLDENTOBC.NS', 'GOLDIAM.NS', 'GOLDTECH.NS', 'GOODLUCK.NS', 'GOPAL.NS', 'GOYALALUM.NS', 'GPIL.NS', 'GPPL.NS', 'GPTHEALTH.NS', 'GPTINFRA.NS', 'GRANULES.NS', 'GRAPHITE.NS', 'GRASIM.NS', 'GRAVITA.NS', 'GREAVESCOT.NS', 'GREENLAM.NS', 'GREENPANEL.NS', 'GREENPLY.NS', 'GREENPOWER.NS', 'GRINDWELL.NS', 'GRINFRA.NS', 'GRMOVER.NS', 'GROBTEA.NS', 'GRPLTD.NS', 'GRSE.NS', 'GRWRHITECH.NS', 'GSFC.NS', 'GSLSU.NS', 'GSPL.NS', 'GSS.NS', 'GTECJAINX.NS', 'GTL.NS', 'GTLINFRA.NS', 'GTPL.NS', 'GUFICBIO.NS', 'GUJALKALI.NS', 'GUJAPOLLO.NS', 'GUJGASLTD.NS', 'GUJRAFFIA.NS', 'GUJTHEM.NS', 'GULFOILLUB.NS', 'GULFPETRO.NS', 'GULPOLY.NS', 'GVKPIL.NS', 'GVPTECH.NS', 'GVPTECH-RE.NS', 'GVT&D.NS', 'HAL.NS', 'HAPPSTMNDS.NS', 'HAPPYFORGE.NS', 'HARDWYN.NS', 'HARIOMPIPE.NS', 'HARRMALAYA.NS', 'HARSHA.NS', 'HATHWAY.NS', 'HATSUN.NS', 'HAVELLS.NS', 'HAVISHA.NS', 'HBLENGINE.NS', 'HBSL.NS', 'HCC.NS', 'HCG.NS', 'HCL-INSYS.NS', 'HCLTECH.NS', 'HDBFS.NS', 'HDFCAMC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HEADSUP.NS', 'HECPROJECT.NS', 'HEG.NS', 'HEIDELBERG.NS', 'HEMIPROP.NS', 'HERANBA.NS', 'HERCULES.NS', 'HERITGFOOD.NS', 'HEROMOTOCO.NS', 'HESTERBIO.NS', 'HEUBACHIND.NS', 'HEXATRADEX.NS', 'HEXT.NS', 'HFCL.NS', 'HGINFRA.NS', 'HGS.NS', 'HIKAL.NS', 'HILTON.NS', 'HIMATSEIDE.NS', 'HINDALCO.NS', 'HINDCOMPOS.NS', 'HINDCON.NS', 'HINDCOPPER.NS', 'HINDMOTORS.NS', 'HINDOILEXP.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'HINDWAREAP.NS', 'HINDZINC.NS', 'HIRECT.NS', 'HISARMETAL.NS', 'HITECH.NS', 'HITECHCORP.NS', 'HITECHGEAR.NS', 'HLEGLAS.NS', 'HLVLTD.NS', 'HMAAGRO.NS', 'HMT.NS', 'HMVL.NS', 'HNDFDS.NS', 'HOMEFIRST.NS', 'HONASA.NS', 'HONAUT.NS', 'HONDAPOWER.NS', 'HOVS.NS', 'HPAL.NS', 'HPIL.NS', 'HPL.NS', 'HSCL.NS', 'HTMEDIA.NS', 'HUBTOWN.NS', 'HUDCO.NS', 'HUHTAMAKI.NS', 'HYBRIDFIN.NS', 'HYUNDAI.NS', 'ICDSLTD.NS', 'ICEMAKE.NS', 'ICICIBANK.NS', 'ICICIGI.NS', 'ICICIPRULI.NS', 'ICIL.NS', 'ICRA.NS', 'IDBI.NS', 'IDEA.NS', 'IDEAFORGE.NS', 'IDFCFIRSTB.NS', 'IEL.NS', 'IEX.NS', 'IFBAGRO.NS', 'IFBIND.NS', 'IFCI.NS', 'IFGLEXPOR.NS', 'IGARASHI.NS', 'IGCL.NS', 'IGIL.NS', 'IGL.NS', 'IGPL.NS', 'IIFL.NS', 'IIFLCAPS.NS', 'IITL.NS', 'IKIO.NS', 'IKS.NS', 'IL&FSENGG.NS', 'IL&FSTRANS.NS', 'IMAGICAA.NS', 'IMFA.NS', 'IMPAL.NS', 'IMPEXFERRO.NS', 'INCREDIBLE.NS', 'INDBANK.NS', 'INDGN.NS', 'INDHOTEL.NS', 'INDIACEM.NS', 'INDIAGLYCO.NS', 'INDIAMART.NS', 'INDIANB.NS', 'INDIANCARD.NS', 'INDIANHUME.NS', 'INDIASHLTR.NS', 'INDIGO.NS', 'INDIGOPNTS.NS', 'INDNIPPON.NS', 'INDOAMIN.NS', 'INDOBORAX.NS', 'INDOCO.NS', 'INDOFARM.NS', 'INDORAMA.NS', 'INDOSTAR.NS', 'INDOTECH.NS', 'INDOTHAI.NS', 'INDOUS.NS', 'INDOWIND.NS', 'INDRAMEDCO.NS', 'INDSWFTLAB.NS', 'INDSWFTLTD.NS', 'INDTERRAIN.NS', 'INDUSINDBK.NS', 'INDUSTOWER.NS', 'INFIBEAM.NS', 'INFOBEAN.NS', 'INFY.NS', 'INGERRAND.NS', 'INNOVACAP.NS', 'INNOVANA.NS', 'INOXGREEN.NS', 'INOXINDIA.NS', 'INOXWIND.NS', 'INSECTICID.NS', 'INSPIRISYS.NS', 'INTELLECT.NS', 'INTENTECH.NS', 'INTERARCH.NS', 'INTLCONV.NS', 'INVENTURE.NS', 'IOB.NS', 'IOC.NS', 'IOLCP.NS', 'IONEXCHANG.NS', 'IPCALAB.NS', 'IPL.NS', 'IRB.NS', 'IRCON.NS', 'IRCTC.NS', 'IREDA.NS', 'IRFC.NS', 'IRIS.NS', 'IRISDOREME.NS', 'IRMENERGY.NS', 'ISFT.NS', 'ISGEC.NS', 'ISHANCH.NS', 'ITC.NS', 'ITCHOTELS.NS', 'ITDC.NS', 'ITDCEM.NS', 'ITI.NS', 'IVC.NS', 'IVP.NS', 'IXIGO.NS', 'IZMO.NS', 'J&KBANK.NS', 'JAGRAN.NS', 'JAGSNPHARM.NS', 'JAIBALAJI.NS', 'JAICORPLTD.NS', 'JAIPURKURT.NS', 'JAMNAAUTO.NS', 'JASH.NS', 'JAYAGROGN.NS', 'JAYBARMARU.NS', 'JAYNECOIND.NS', 'JAYSREETEA.NS', 'JBCHEPHARM.NS', 'JBMA.NS', 'JCHAC.NS', 'JETFREIGHT.NS', 'JGCHEM.NS', 'JHS.NS', 'JINDALPHOT.NS', 'JINDALPOLY.NS', 'JINDALSAW.NS', 'JINDALSTEL.NS', 'JINDRILL.NS', 'JINDWORLD.NS', 'JIOFIN.NS', 'JISLDVREQS.NS', 'JISLJALEQS.NS', 'JITFINFRA.NS', 'JKCEMENT.NS', 'JKIL.NS', 'JKLAKSHMI.NS', 'JKPAPER.NS', 'JKTYRE.NS', 'JLHL.NS', 'JMA.NS', 'JMFINANCIL.NS', 'JNKINDIA.NS', 'JOCIL.NS', 'JPOLYINVST.NS', 'JPPOWER.NS', 'JSFB.NS', 'JSL.NS', 'JSWENERGY.NS', 'JSWHL.NS', 'JSWINFRA.NS', 'JSWSTEEL.NS', 'JTEKTINDIA.NS', 'JTLIND.NS', 'JUBLCPL.NS', 'JUBLFOOD.NS', 'JUBLINGREA.NS', 'JUBLPHARMA.NS', 'JUNIPER.NS', 'JUSTDIAL.NS', 'JWL.NS', 'JYOTHYLAB.NS', 'JYOTICNC.NS', 'JYOTISTRUC.NS', 'KABRAEXTRU.NS', 'KAJARIACER.NS', 'KAKATCEM.NS', 'KALAMANDIR.NS', 'KALPATARU.NS', 'KALYANI.NS', 'KALYANIFRG.NS', 'KALYANKJIL.NS', 'KAMATHOTEL.NS', 'KAMDHENU.NS', 'KAMOPAINTS.NS', 'KANANIIND.NS', 'KANORICHEM.NS', 'KANPRPLA.NS', 'KANSAINER.NS', 'KAPSTON.NS', 'KARMAENG.NS', 'KARURVYSYA.NS', 'KAUSHALYA.NS', 'KAVDEFENCE.NS', 'KAYA.NS', 'KAYNES.NS', 'KCP.NS', 'KCPSUGIND.NS', 'KDDL.NS', 'KEC.NS', 'KECL.NS', 'KEEPLEARN.NS', 'KEI.NS', 'KELLTONTEC.NS', 'KERNEX.NS', 'KESORAMIND.NS', 'KEYFINSERV.NS', 'KFINTECH.NS', 'KHADIM.NS', 'KHAICHEM.NS', 'KHAITANLTD.NS', 'KHANDSE.NS', 'KICL.NS', 'KILITCH.NS', 'KIMS.NS', 'KINGFA.NS', 'KIOCL.NS', 'KIRIINDUS.NS', 'KIRLOSBROS.NS', 'KIRLOSENG.NS', 'KIRLOSIND.NS', 'KIRLPNU.NS', 'KITEX.NS', 'KKCL.NS', 'KMEW.NS', 'KMSUGAR.NS', 'KNRCON.NS', 'KOHINOOR.NS', 'KOKUYOCMLN.NS', 'KOLTEPATIL.NS', 'KOPRAN.NS', 'KOTAKBANK.NS', 'KOTARISUG.NS', 'KOTHARIPET.NS', 'KOTHARIPRO.NS', 'KPEL.NS', 'KPIGREEN.NS', 'KPIL.NS', 'KPITTECH.NS', 'KPRMILL.NS', 'KRBL.NS', 'KREBSBIO.NS', 'KRIDHANINF.NS', 'KRISHANA.NS', 'KRISHIVAL.NS', 'KRITI.NS', 'KRITIKA.NS', 'KRITINUT.NS', 'KRN.NS', 'KRONOX.NS', 'KROSS.NS', 'KRSNAA.NS', 'KRYSTAL.NS', 'KSB.NS', 'KSCL.NS', 'KSHITIJPOL.NS', 'KSL.NS', 'KSOLVES.NS', 'KTKBANK.NS', 'KUANTUM.NS', 'LAGNAM.NS', 'LAKPRE.NS', 'LAL.NS', 'LALPATHLAB.NS', 'LAMBODHARA.NS', 'LANCORHOL.NS', 'LANDMARK.NS', 'LAOPALA.NS', 'LASA.NS', 'LATENTVIEW.NS', 'LATTEYS.NS', 'LAURUSLABS.NS', 'LAXMICOT.NS', 'LAXMIDENTL.NS', 'LCCINFOTEC.NS', 'LEMONTREE.NS', 'LEXUS.NS', 'LFIC.NS', 'LGBBROSLTD.NS', 'LGHL.NS', 'LIBAS.NS', 'LIBERTSHOE.NS', 'LICHSGFIN.NS', 'LICI.NS', 'LIKHITHA.NS', 'LINC.NS', 'LINCOLN.NS', 'LINDEINDIA.NS', 'LLOYDSENGG.NS', 'LLOYDSENT.NS', 'LLOYDSME.NS', 'LMW.NS', 'LODHA.NS', 'LOKESHMACH.NS', 'LORDSCHLO.NS', 'LOTUSEYE.NS', 'LOVABLE.NS', 'LOYALTEX.NS', 'LPDC.NS', 'LT.NS', 'LTF.NS', 'LTFOODS.NS', 'LTIM.NS', 'LTTS.NS', 'LUMAXIND.NS', 'LUMAXTECH.NS', 'LUPIN.NS', 'LUXIND.NS', 'LXCHEM.NS', 'LYKALABS.NS', 'LYPSAGEMS.NS', 'M&M.NS', 'M&MFIN.NS', 'MAANALU.NS', 'MACPOWER.NS', 'MADHAV.NS', 'MADHUCON.NS', 'MADRASFERT.NS', 'MAGADSUGAR.NS', 'MAGNUM.NS', 'MAHABANK.NS', 'MAHAPEXLTD.NS', 'MAHASTEEL.NS', 'MAHEPC.NS', 'MAHESHWARI.NS', 'MAHLIFE.NS', 'MAHLOG.NS', 'MAHSCOOTER.NS', 'MAHSEAMLES.NS', 'MAITHANALL.NS', 'MALLCOM.NS', 'MALUPAPER.NS', 'MAMATA.NS', 'MANAKALUCO.NS', 'MANAKCOAT.NS', 'MANAKSIA.NS', 'MANAKSTEEL.NS', 'MANALIPETC.NS', 'MANAPPURAM.NS', 'MANBA.NS', 'MANCREDIT.NS', 'MANGALAM.NS', 'MANGCHEFER.NS', 'MANGLMCEM.NS', 'MANINDS.NS', 'MANINFRA.NS', 'MANKIND.NS', 'MANOMAY.NS', 'MANORAMA.NS', 'MANORG.NS', 'MANUGRAPH.NS', 'MANYAVAR.NS', 'MAPMYINDIA.NS', 'MARALOVER.NS', 'MARATHON.NS', 'MARICO.NS', 'MARINE.NS', 'MARKSANS.NS', 'MARUTI.NS', 'MASFIN.NS', 'MASKINVEST.NS', 'MASTEK.NS', 'MASTERTR.NS', 'MATRIMONY.NS', 'MAWANASUG.NS', 'MAXESTATES.NS', 'MAXHEALTH.NS', 'MAXIND.NS', 'MAYURUNIQ.NS', 'MAZDA.NS', 'MAZDOCK.NS', 'MBAPL.NS', 'MBLINFRA.NS', 'MCL.NS', 'MCLEODRUSS.NS', 'MCLOUD.NS', 'MCX.NS', 'MEDANTA.NS', 'MEDIASSIST.NS', 'MEDICAMEQ.NS', 'MEDICO.NS', 'MEDPLUS.NS', 'MEGASOFT.NS', 'MEGASTAR.NS', 'MENONBE.NS', 'MEP.NS', 'METROBRAND.NS', 'METROPOLIS.NS', 'MFML.NS', 'MFSL.NS', 'MGEL.NS', 'MGL.NS', 'MHLXMIRU.NS', 'MHRIL.NS', 'MICEL.NS', 'MIDHANI.NS', 'MINDACORP.NS', 'MINDTECK.NS', 'MIRC-RE.NS', 'MIRCELECTR.NS', 'MIRZAINT.NS', 'MITCON.NS', 'MITTAL.NS', 'MKPL.NS', 'MMFL.NS', 'MMP.NS', 'MMTC.NS', 'MOBIKWIK.NS', 'MODIRUBBER.NS', 'MODISONLTD.NS', 'MODTHREAD.NS', 'MOHITIND.NS', 'MOIL.NS', 'MOKSH.NS', 'MOL.NS', 'MOLDTECH.NS', 'MOLDTKPAC.NS', 'MONARCH.NS', 'MONTECARLO.NS', 'MOREPENLAB.NS', 'MOSCHIP.NS', 'MOTHERSON.NS', 'MOTILALOFS.NS', 'MOTISONS.NS', 'MOTOGENFIN.NS', 'MPHASIS.NS', 'MPSLTD.NS', 'MRF.NS', 'MRPL.NS', 'MSPL.NS', 'MSTCLTD.NS', 'MSUMI.NS', 'MTARTECH.NS', 'MTEDUCARE.NS', 'MTNL.NS', 'MUFIN.NS', 'MUFTI.NS', 'MUKANDLTD.NS', 'MUKKA.NS', 'MUKTAARTS.NS', 'MUNJALAU.NS', 'MUNJALSHOW.NS', 'MURUDCERA.NS', 'MUTHOOTCAP.NS', 'MUTHOOTFIN.NS', 'MUTHOOTMF.NS', 'MVGJL.NS', 'NACLIND.NS', 'NAGAFERT.NS', 'NAGREEKCAP.NS', 'NAGREEKEXP.NS', 'NAHARCAP.NS', 'NAHARINDUS.NS', 'NAHARPOLY.NS', 'NAHARSPING.NS', 'NAM-INDIA.NS', 'NARMADA.NS', 'NATCAPSUQ.NS', 'NATCOPHARM.NS', 'NATHBIOGEN.NS', 'NATIONALUM.NS', 'NAUKRI.NS', 'NAVA.NS', 'NAVINFLUOR.NS', 'NAVKARCORP.NS', 'NAVKARURB.NS', 'NAVNETEDUL.NS', 'NAZARA.NS', 'NBCC.NS', 'NBIFIN.NS', 'NCC.NS', 'NCLIND.NS', 'NDGL.NS', 'NDL.NS', 'NDLVENTURE.NS', 'NDRAUTO.NS', 'NDTV.NS', 'NECCLTD.NS', 'NECLIFE.NS', 'NELCAST.NS', 'NELCO.NS', 'NEOGEN.NS', 'NESCO.NS', 'NESTLEIND.NS', 'NETWEB.NS', 'NETWORK18.NS', 'NEULANDLAB.NS', 'NEWGEN.NS', 'NEXTMEDIA.NS', 'NFL.NS', 'NGIL.NS', 'NGLFINE.NS', 'NH.NS', 'NHPC.NS', 'NIACL.NS', 'NIBE.NS', 'NIBL.NS', 'NIITLTD.NS', 'NIITMTS.NS', 'NILAINFRA.NS', 'NILASPACES.NS', 'NILKAMAL.NS', 'NINSYS.NS', 'NIPPOBATRY.NS', 'NIRAJ.NS', 'NIRAJISPAT.NS', 'NITCO.NS', 'NITINSPIN.NS', 'NITIRAJ.NS', 'NIVABUPA.NS', 'NKIND.NS', 'NLCINDIA.NS', 'NMDC.NS', 'NOCIL.NS', 'NOIDATOLL.NS', 'NORBTEAEXP.NS', 'NORTHARC.NS', 'NOVAAGRI.NS', 'NPST.NS', 'NRAIL.NS', 'NRBBEARING.NS', 'NRL.NS', 'NSIL.NS', 'NSLNISP.NS', 'NTPC.NS', 'NTPCGREEN.NS', 'NUCLEUS.NS', 'NURECA.NS', 'NUVAMA.NS', 'NUVOCO.NS', 'NYKAA.NS', 'OAL.NS', 'OBCL.NS', 'OBEROIRLTY.NS', 'OCCLLTD.NS', 'ODIGMA.NS', 'OFSS.NS', 'OIL.NS', 'OILCOUNTUB.NS', 'OLAELEC.NS', 'OLECTRA.NS', 'OMAXAUTO.NS', 'OMAXE.NS', 'OMINFRAL.NS', 'ONELIFECAP.NS', 'ONEPOINT.NS', 'ONESOURCE.NS', 'ONGC.NS', 'ONMOBILE.NS', 'ONWARDTEC.NS', 'OPTIEMUS.NS', 'ORBTEXP.NS', 'ORCHASP.NS', 'ORCHPHARMA.NS', 'ORICONENT.NS', 'ORIENTALTL.NS', 'ORIENTBELL.NS', 'ORIENTCEM.NS', 'ORIENTCER.NS', 'ORIENTELEC.NS', 'ORIENTHOT.NS', 'ORIENTLTD.NS', 'ORIENTPPR.NS', 'ORIENTTECH.NS', 'ORISSAMINE.NS', 'ORTEL.NS', 'ORTINGLOBE.NS', 'OSIAHYPER.NS', 'OSWALAGRO.NS', 'OSWALGREEN.NS', 'OSWALPUMPS.NS', 'OSWALSEEDS.NS', 'PAGEIND.NS', 'PAISALO.NS', 'PAKKA.NS', 'PALASHSECU.NS', 'PALREDTEC.NS', 'PANACEABIO.NS', 'PANACHE.NS', 'PANAMAPET.NS', 'PANSARI.NS', 'PAR.NS', 'PARACABLES.NS', 'PARADEEP.NS', 'PARAGMILK.NS', 'PARAS.NS', 'PARASPETRO.NS', 'PARKHOTELS.NS', 'PARSVNATH.NS', 'PASUPTAC.NS', 'PATANJALI.NS', 'PATELENG.NS', 'PATINTLOG.NS', 'PAVNAIND.NS', 'PAYTM.NS', 'PCBL.NS', 'PCJEWELLER.NS', 'PDMJEPAPER.NS', 'PDSL.NS', 'PEARLPOLY.NS', 'PEL.NS', 'PENIND.NS', 'PENINLAND.NS', 'PERSISTENT.NS', 'PETRONET.NS', 'PFC.NS', 'PFIZER.NS', 'PFOCUS.NS', 'PFS.NS', 'PGEL.NS', 'PGHH.NS', 'PGHL.NS', 'PGIL.NS', 'PHOENIXLTD.NS', 'PICCADIL.NS', 'PIDILITIND.NS', 'PIGL.NS', 'PIIND.NS', 'PILANIINVS.NS', 'PILITA.NS', 'PIONEEREMB.NS', 'PITTIENG.NS', 'PIXTRANS.NS', 'PKTEA.NS', 'PLASTIBLEN.NS', 'PLATIND.NS', 'PLAZACABLE.NS', 'PNB.NS', 'PNBGILTS.NS', 'PNBHOUSING.NS', 'PNC.NS', 'PNCINFRA.NS', 'PNGJL.NS', 'POCL.NS', 'PODDARMENT.NS', 'POKARNA.NS', 'POLICYBZR.NS', 'POLYCAB.NS', 'POLYMED.NS', 'POLYPLEX.NS', 'PONNIERODE.NS', 'POONAWALLA.NS', 'POWERGRID.NS', 'POWERINDIA.NS', 'POWERMECH.NS', 'PPAP.NS', 'PPL.NS', 'PPLPHARMA.NS', 'PRABHA.NS', 'PRAENG.NS', 'PRAJIND.NS', 'PRAKASH.NS', 'PRAKASHSTL.NS', 'PRAXIS.NS', 'PRECAM.NS', 'PRECOT.NS', 'PRECWIRE.NS', 'PREMEXPLN.NS', 'PREMIER.NS', 'PREMIERENE.NS', 'PREMIERPOL.NS', 'PRESTIGE.NS', 'PRICOLLTD.NS', 'PRIMESECU.NS', 'PRIMO.NS', 'PRINCEPIPE.NS', 'PRITI.NS', 'PRITIKAUTO.NS', 'PRIVISCL.NS', 'PROSTARM.NS', 'PROTEAN.NS', 'PROZONER.NS', 'PRSMJOHNSN.NS', 'PRUDENT.NS', 'PRUDMOULI.NS', 'PSB.NS', 'PSPPROJECT.NS', 'PTC.NS', 'PTCIL.NS', 'PTL.NS', 'PUNJABCHEM.NS', 'PURVA.NS', 'PVP.NS', 'PVRINOX.NS', 'PVSL.NS', 'PYRAMID.NS', 'QPOWER.NS', 'QUADFUTURE.NS', 'QUESS.NS', 'QUICKHEAL.NS', 'RACE.NS', 'RACLGEAR.NS', 'RADAAN.NS', 'RADHIKAJWE.NS', 'RADIANTCMS.NS', 'RADICO.NS', 'RADIOCITY.NS', 'RAILTEL.NS', 'RAIN.NS', 'RAINBOW.NS', 'RAJESHEXPO.NS', 'RAJMET.NS', 'RAJOOENG.NS', 'RAJRATAN.NS', 'RAJRILTD.NS', 'RAJSREESUG.NS', 'RAJTV.NS', 'RALLIS.NS', 'RAMANEWS.NS', 'RAMAPHO.NS', 'RAMASTEEL.NS', 'RAMCOCEM.NS', 'RAMCOIND.NS', 'RAMCOSYS.NS', 'RAMKY.NS', 'RAMRAT.NS', 'RANASUG.NS', 'RANEHOLDIN.NS', 'RATEGAIN.NS', 'RATNAMANI.NS', 'RATNAVEER.NS', 'RAYMOND.NS', 'RAYMONDLSL.NS', 'RAYMONDREL.NS', 'RBA.NS', 'RBLBANK.NS', 'RBZJEWEL.NS', 'RCF.NS', 'RECLTD.NS', 'REDINGTON.NS', 'REDTAPE.NS', 'REFEX.NS', 'REGENCERAM.NS', 'RELAXO.NS', 'RELCHEMQ.NS', 'RELIABLE.NS', 'RELIANCE.NS', 'RELIGARE.NS', 'RELINFRA.NS', 'RELTD.NS', 'REMSONSIND.NS', 'RENUKA.NS', 'REPCOHOME.NS', 'REPL.NS', 'REPRO.NS', 'RESPONIND.NS', 'RETAIL.NS', 'RGL.NS', 'RHFL.NS', 'RHIM.NS', 'RHL.NS', 'RICOAUTO.NS', 'RIIL.NS', 'RISHABH.NS', 'RITCO.NS', 'RITES.NS', 'RKDL.NS', 'RKEC.NS', 'RKFORGE.NS', 'RKSWAMY.NS', 'RML.NS', 'ROHLTD.NS', 'ROLEXRINGS.NS', 'ROLLT.NS', 'ROLTA.NS', 'ROML.NS', 'ROSSARI.NS', 'ROSSELLIND.NS', 'ROSSTECH.NS', 'ROTO.NS', 'ROUTE.NS', 'RPEL.NS', 'RPGLIFE.NS', 'RPOWER.NS', 'RPPINFRA.NS', 'RPPL.NS', 'RPSGVENT.NS', 'RPTECH.NS', 'RRKABEL.NS', 'RSSOFTWARE.NS', 'RSWM.NS', 'RSYSTEMS.NS', 'RTNINDIA.NS', 'RTNPOWER.NS', 'RUBFILA.NS', 'RUBYMILLS.NS', 'RUCHINFRA.NS', 'RUCHIRA.NS', 'RUPA.NS', 'RUSHIL.NS', 'RUSTOMJEE.NS', 'RVHL.NS', 'RVNL.NS', 'RVTH.NS', 'S&SPOWER.NS', 'SABEVENTS.NS', 'SABTNL.NS', 'SADBHAV.NS', 'SADBHIN.NS', 'SADHNANIQ.NS', 'SAFARI.NS', 'SAGARDEEP.NS', 'SAGCEM.NS', 'SAGILITY.NS', 'SAH.NS', 'SAHYADRI.NS', 'SAIL.NS', 'SAILIFE.NS', 'SAKAR.NS', 'SAKHTISUG.NS', 'SAKSOFT.NS', 'SAKUMA.NS', 'SALASAR.NS', 'SALONA.NS', 'SALSTEEL.NS', 'SALZERELEC.NS', 'SAMBHAAV.NS', 'SAMBHV.NS', 'SAMHI.NS', 'SAMMAANCAP.NS', 'SAMPANN.NS', 'SANATHAN.NS', 'SANDESH.NS', 'SANDHAR.NS', 'SANDUMA.NS', 'SANGAMIND.NS', 'SANGHIIND.NS', 'SANGHVIMOV.NS', 'SANGINITA.NS', 'SANOFI.NS', 'SANOFICONR.NS', 'SANSERA.NS', 'SANSTAR.NS', 'SANWARIA.NS', 'SAPPHIRE.NS', 'SARDAEN.NS', 'SAREGAMA.NS', 'SARLAPOLY.NS', 'SARVESHWAR.NS', 'SASKEN.NS', 'SASTASUNDR.NS', 'SATIA.NS', 'SATIN.NS', 'SAURASHCEM.NS', 'SBC.NS', 'SBCL.NS', 'SBFC.NS', 'SBGLP.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SBIN.NS', 'SCHAEFFLER.NS', 'SCHAND.NS', 'SCHNEIDER.NS', 'SCI.NS', 'SCILAL.NS', 'SCODATUBES.NS', 'SCPL.NS', 'SDBL.NS', 'SEAMECLTD.NS', 'SECMARK.NS', 'SECURKLOUD.NS', 'SEJALLTD.NS', 'SELAN.NS', 'SELMC.NS', 'SEMAC.NS', 'SENCO.NS', 'SENORES.NS', 'SEPC.NS', 'SEQUENT.NS', 'SERVOTECH.NS', 'SESHAPAPER.NS', 'SETCO.NS', 'SETUINFRA.NS', 'SFL.NS', 'SGIL.NS', 'SGL.NS', 'SGLTL.NS', 'SHAH.NS', 'SHAHALLOYS.NS', 'SHAILY.NS', 'SHAKTIPUMP.NS', 'SHALBY.NS', 'SHALPAINTS.NS', 'SHANKARA.NS', 'SHANTI.NS', 'SHANTIGEAR.NS', 'SHARDACROP.NS', 'SHARDAMOTR.NS', 'SHAREINDIA.NS', 'SHEKHAWATI.NS', 'SHEMAROO.NS', 'SHILPAMED.NS', 'SHIVALIK.NS', 'SHIVAMAUTO.NS', 'SHIVAMILLS.NS', 'SHIVATEX.NS', 'SHK.NS', 'SHOPERSTOP.NS', 'SHRADHA.NS', 'SHREDIGCEM.NS', 'SHREECEM.NS', 'SHREEPUSHK.NS', 'SHREERAMA.NS', 'SHRENIK.NS', 'SHREYANIND.NS', 'SHRIPISTON.NS', 'SHRIRAMFIN.NS', 'SHRIRAMPPS.NS', 'SHYAMCENT.NS', 'SHYAMMETL.NS', 'SHYAMTEL.NS', 'SICALLOG.NS', 'SIEMENS.NS', 'SIGACHI.NS', 'SIGIND.NS', 'SIGMA.NS', 'SIGNATURE.NS', 'SIGNPOST.NS', 'SIKKO.NS', 'SIL.NS', 'SILGO.NS', 'SILINV.NS', 'SILLYMONKS.NS', 'SILVERTUC.NS', 'SIMBHALS.NS', 'SIMPLEXINF.NS', 'SINCLAIR.NS', 'SINDHUTRAD.NS', 'SINTERCOM.NS', 'SIRCA.NS', 'SIS.NS', 'SITINET.NS', 'SIYSIL.NS', 'SJS.NS', 'SJVN.NS', 'SKFINDIA.NS', 'SKIPPER.NS', 'SKMEGGPROD.NS', 'SKYGOLD.NS', 'SMARTLINK.NS', 'SMCGLOBAL.NS', 'SMLISUZU.NS', 'SMLT.NS', 'SMSLIFE.NS', 'SMSPHARMA.NS', 'SNOWMAN.NS', 'SOBHA.NS', 'SOFTTECH.NS', 'SOLARA.NS', 'SOLARINDS.NS', 'SOMANYCERA.NS', 'SOMATEX.NS', 'SOMICONVEY.NS', 'SONACOMS.NS', 'SONAMLTD.NS', 'SONATSOFTW.NS', 'SOTL.NS', 'SOUTHBANK.NS', 'SOUTHWEST.NS', 'SPAL.NS', 'SPANDANA.NS', 'SPARC.NS', 'SPCENET.NS', 'SPECIALITY.NS', 'SPECTRUM.NS', 'SPENCERS.NS', 'SPIC.NS', 'SPLIL.NS', 'SPLPETRO.NS', 'SPMLINFRA.NS', 'SPORTKING.NS', 'SRD.NS', 'SREEL.NS', 'SRF.NS', 'SRGHFL.NS', 'SRHHYPOLTD.NS', 'SRM.NS', 'SRPL.NS', 'SSDL.NS', 'SSWL.NS', 'STALLION.NS', 'STANLEY.NS', 'STAR.NS', 'STARCEMENT.NS', 'STARHEALTH.NS', 'STARPAPER.NS', 'STARTECK.NS', 'STCINDIA.NS', 'STEELCAS.NS', 'STEELCITY.NS', 'STEELXIND.NS', 'STEL.NS', 'STERTOOLS.NS', 'STLTECH.NS', 'STOVEKRAFT.NS', 'STYLAMIND.NS', 'STYLEBAAZA.NS', 'STYRENIX.NS', 'SUBEXLTD.NS', 'SUBROS.NS', 'SUDARSCHEM.NS', 'SUKHJITS.NS', 'SULA.NS', 'SUMEETINDS.NS', 'SUMICHEM.NS', 'SUMIT.NS', 'SUMMITSEC.NS', 'SUNCLAY.NS', 'SUNDARAM.NS', 'SUNDARMFIN.NS', 'SUNDARMHLD.NS', 'SUNDRMBRAK.NS', 'SUNDRMFAST.NS', 'SUNDROP.NS', 'SUNFLAG.NS', 'SUNPHARMA.NS', 'SUNTECK.NS', 'SUNTV.NS', 'SUPERHOUSE.NS', 'SUPERSPIN.NS', 'SUPRAJIT.NS', 'SUPREME.NS', 'SUPREMEIND.NS', 'SUPREMEINF.NS', 'SUPRIYA.NS', 'SURAJEST.NS', 'SURAJLTD.NS', 'SURAKSHA.NS', 'SURANASOL.NS', 'SURANAT&P.NS', 'SURYALAXMI.NS', 'SURYAROSNI.NS', 'SURYODAY.NS', 'SUTLEJTEX.NS', 'SUVEN.NS', 'SUVIDHAA.NS', 'SUYOG.NS', 'SUZLON.NS', 'SVLL.NS', 'SVPGLOB.NS', 'SWANENERGY.NS', 'SWARAJENG.NS', 'SWELECTES.NS', 'SWIGGY.NS', 'SWSOLAR.NS', 'SYMPHONY.NS', 'SYNCOMF.NS', 'SYNGENE.NS', 'SYRMA.NS', 'TAINWALCHM.NS', 'TAJGVK.NS', 'TAKE.NS', 'TALBROAUTO.NS', 'TANLA.NS', 'TARACHAND.NS', 'TARAPUR.NS', 'TARC.NS', 'TARIL.NS', 'TARMAT.NS', 'TARSONS.NS', 'TASTYBITE.NS', 'TATACHEM.NS', 'TATACOMM.NS', 'TATACONSUM.NS', 'TATAELXSI.NS', 'TATAINVEST.NS', 'TATAMOTORS.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TATATECH.NS', 'TATVA.NS', 'TBOTEK.NS', 'TBZ.NS', 'TCI.NS', 'TCIEXP.NS', 'TCIFINANCE.NS', 'TCPLPACK.NS', 'TCS.NS', 'TDPOWERSYS.NS', 'TEAMLEASE.NS', 'TECHM.NS', 'TECHNOE.NS', 'TECILCHEM.NS', 'TEGA.NS', 'TEJASNET.NS', 'TEMBO.NS', 'TERASOFT.NS', 'TEXINFRA.NS', 'TEXMOPIPES.NS', 'TEXRAIL.NS', 'TFCILTD.NS', 'TFL.NS', 'TGBHOTELS.NS', 'THANGAMAYL.NS', 'THEINVEST.NS', 'THEJO.NS', 'THELEELA.NS', 'THEMISMED.NS', 'THERMAX.NS', 'THOMASCOOK.NS', 'THOMASCOTT.NS', 'THYROCARE.NS', 'TI.NS', 'TICL.NS', 'TIIL.NS', 'TIINDIA.NS', 'TIJARIA.NS', 'TIL.NS', 'TIMESGTY.NS', 'TIMETECHNO.NS', 'TIMKEN.NS', 'TINNARUBR.NS', 'TIPSFILMS.NS', 'TIPSMUSIC.NS', 'TIRUMALCHM.NS', 'TIRUPATIFL.NS', 'TITAGARH.NS', 'TITAN.NS', 'TMB.NS', 'TNPETRO.NS', 'TNPL.NS', 'TNTELE.NS', 'TOKYOPLAST.NS', 'TOLINS.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TOTAL.NS', 'TOUCHWOOD.NS', 'TPHQ.NS', 'TPLPLASTEH.NS', 'TRACXN.NS', 'TRANSRAILL.NS', 'TRANSWORLD.NS', 'TRAVELFOOD.NS', 'TREEHOUSE.NS', 'TREJHARA.NS', 'TREL.NS', 'TRENT.NS', 'TRF.NS', 'TRIDENT.NS', 'TRIGYN.NS', 'TRITURBINE.NS', 'TRIVENI.NS', 'TRU.NS', 'TTKHLTCARE.NS', 'TTKPRESTIG.NS', 'TTL.NS', 'TTML.NS', 'TVSELECT.NS', 'TVSHLTD.NS', 'TVSMOTOR.NS', 'TVSSCS.NS', 'TVSSRICHAK.NS', 'TVTODAY.NS', 'TVVISION.NS', 'UBL.NS', 'UCAL.NS', 'UCOBANK.NS', 'UDAICEMENT.NS', 'UDS.NS', 'UFLEX.NS', 'UFO.NS', 'UGARSUGAR.NS', 'UGROCAP.NS', 'UJJIVANSFB.NS', 'ULTRACEMCO.NS', 'UMAEXPORTS.NS', 'UMESLTD.NS', 'UMIYA-MRO.NS', 'UNICHEMLAB.NS', 'UNIDT.NS', 'UNIECOM.NS', 'UNIENTER.NS', 'UNIINFO.NS', 'UNIMECH.NS', 'UNIONBANK.NS', 'UNIPARTS.NS', 'UNITDSPR.NS', 'UNITECH.NS', 'UNITEDPOLY.NS', 'UNITEDTEA.NS', 'UNIVASTU.NS', 'UNIVCABLES.NS', 'UNIVPHOTO.NS', 'UNOMINDA.NS', 'UPL.NS', 'URAVIDEF.NS', 'URJA.NS', 'USHAMART.NS', 'USK.NS', 'UTIAMC.NS', 'UTKARSHBNK.NS', 'UTTAMSUGAR.NS', 'UYFINCORP.NS', 'V2RETAIL.NS', 'VADILALIND.NS', 'VAIBHAVGBL.NS', 'VAISHALI.NS', 'VAKRANGEE.NS', 'VALIANTLAB.NS', 'VALIANTORG.NS', 'VARDHACRLC.NS', 'VARDMNPOLY.NS', 'VARROC.NS', 'VASCONEQ.NS', 'VASWANI.NS', 'VBL.NS', 'VCL.NS', 'VEDL.NS', 'VEEDOL.NS', 'VENKEYS.NS', 'VENTIVE.NS', 'VENUSPIPES.NS', 'VENUSREM.NS', 'VERANDA.NS', 'VERTOZ.NS', 'VESUVIUS.NS', 'VETO.NS', 'VGUARD.NS', 'VHL.NS', 'VHLTD.NS', 'VIDHIING.NS', 'VIJAYA.NS', 'VIJIFIN.NS', 'VIKASECO.NS', 'VIKASLIFE.NS', 'VIMTALABS.NS', 'VINATIORGA.NS', 'VINCOFE.NS', 'VINDHYATEL.NS', 'VINEETLAB.NS', 'VINNY.NS', 'VINYLINDIA.NS', 'VIPCLOTHNG.NS', 'VIPIND.NS', 'VIPULLTD.NS', 'VIRINCHI.NS', 'VISAKAIND.NS', 'VISASTEEL.NS', 'VISHNU.NS', 'VISHWARAJ.NS', 'VIVIDHA.NS', 'VLEGOV.NS', 'VLSFINANCE.NS', 'VMART.NS', 'VMM.NS', 'VOLTAMP.NS', 'VOLTAS.NS', 'VPRPL.NS', 'VRAJ.NS', 'VRLLOG.NS', 'VSSL.NS', 'VSTIND.NS', 'VSTL.NS', 'VSTTILLERS.NS', 'VTL.NS', 'WAAREEENER.NS', 'WAAREERTL.NS', 'WABAG.NS', 'WALCHANNAG.NS', 'WANBURY.NS', 'WCIL.NS', 'WEALTH.NS', 'WEBELSOLAR.NS', 'WEIZMANIND.NS', 'WEL.NS', 'WELCORP.NS', 'WELENT.NS', 'WELINV.NS', 'WELSPUNLIV.NS', 'WENDT.NS', 'WESTLIFE.NS', 'WEWIN.NS', 'WHEELS.NS', 'WHIRLPOOL.NS', 'WILLAMAGOR.NS', 'WINDLAS.NS', 'WINDMACHIN.NS', 'WINSOME.NS', 'WIPL.NS', 'WIPRO.NS', 'WOCKPHARMA.NS', 'WONDERLA.NS', 'WORTH.NS', 'WSI.NS', 'WSTCSTPAPR.NS', 'XCHANGING.NS', 'XELPMOC.NS', 'XPROINDIA.NS', 'XTGLOBAL.NS', 'YAARI.NS', 'YASHO.NS', 'YATHARTH.NS', 'YATRA.NS', 'YESBANK.NS', 'YUKEN.NS', 'ZAGGLE.NS', 'ZEEL.NS', 'ZEELEARN.NS', 'ZEEMEDIA.NS', 'ZENITHEXPO.NS', 'ZENITHSTL.NS', 'ZENSARTECH.NS', 'ZENTEC.NS', 'ZFCVINDIA.NS', 'ZIMLAB.NS', 'ZODIAC.NS', 'ZODIACLOTH.NS', 'ZOTA.NS', 'ZUARI.NS', 'ZUARIIND.NS', 'ZYDUSLIFE.NS', 'ZYDUSWELL.NS'
]

# Session state initialization
if 'all_stocks_data' not in st.session_state:
    st.session_state.all_stocks_data = []
if 'filtered_stocks' not in st.session_state:
    st.session_state.filtered_stocks = []
if 'last_scan_time' not in st.session_state:
    st.session_state.last_scan_time = "Never"

def calculate_rsi(prices, period=14):
    """Calculate RSI (Relative Strength Index)"""
    if len(prices) < period + 1:
        return None
    
    deltas = np.diff(prices)
    gains = np.where(deltas > 0, deltas, 0)
    losses = np.where(deltas < 0, -deltas, 0)
    
    avg_gain = np.mean(gains[:period])
    avg_loss = np.mean(losses[:period])
    
    for i in range(period, len(deltas)):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
    
    if avg_loss == 0:
        return 100
    
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def calculate_macd(prices, fast=12, slow=26, signal=9):
    """Calculate MACD (Moving Average Convergence Divergence)"""
    if len(prices) < slow:
        return None, None, None
    
    # Calculate EMAs
    ema_fast = pd.Series(prices).ewm(span=fast).mean()
    ema_slow = pd.Series(prices).ewm(span=slow).mean()
    
    # MACD line
    macd_line = ema_fast - ema_slow
    
    # Signal line
    signal_line = macd_line.ewm(span=signal).mean()
    
    # Histogram
    histogram = macd_line - signal_line
    
    return macd_line.iloc[-1], signal_line.iloc[-1], histogram.iloc[-1]

def calculate_bollinger_bands(prices, period=20, std_dev=2):
    """Calculate Bollinger Bands"""
    if len(prices) < period:
        return None, None, None
    
    sma = np.mean(prices[-period:])
    std = np.std(prices[-period:])
    
    upper_band = sma + (std * std_dev)
    lower_band = sma - (std * std_dev)
    
    return upper_band, sma, lower_band

def calculate_moving_averages(prices):
    """Calculate various moving averages"""
    ma_5 = np.mean(prices[-5:]) if len(prices) >= 5 else None
    ma_10 = np.mean(prices[-10:]) if len(prices) >= 10 else None
    ma_20 = np.mean(prices[-20:]) if len(prices) >= 20 else None
    ma_50 = np.mean(prices[-50:]) if len(prices) >= 50 else None
    
    return ma_5, ma_10, ma_20, ma_50

@lru_cache(maxsize=1000)
def get_comprehensive_stock_data(symbol, stoch_period=14, rsi_period=14):
    """
    Fetch stock data and calculate all technical indicators
    """
    try:
        # Get historical data for indicator calculations
        url = f"https://query1.finance.yahoo.com/v8/finance/chart/{symbol}?interval=1d&range=3mo"
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=10)
        data = response.json()
        
        result = data['chart']['result'][0]
        meta = result['meta']
        
        # Get OHLC data
        quotes = result['indicators']['quote'][0]
        timestamps = result['timestamp']
        
        high_prices = [h for h in quotes['high'] if h is not None]
        low_prices = [l for l in quotes['low'] if l is not None]
        close_prices = [c for c in quotes['close'] if c is not None]
        volumes = [v for v in quotes['volume'] if v is not None]
        
        if len(close_prices) < max(stoch_period, rsi_period, 20):
            return None
        
        # Basic price info
        current_price = meta['regularMarketPrice']
        previous_close = meta['chartPreviousClose']
        change = current_price - previous_close
        change_percent = (change / previous_close) * 100
        
        # Calculate 1-day price change (yesterday's close vs today's price)
        yesterday_close = close_prices[-2] if len(close_prices) > 1 else previous_close
        one_day_change = current_price - yesterday_close
        one_day_change_percent = (one_day_change / yesterday_close) * 100
        
        # Calculate Stochastic %K
        current_close = close_prices[-1]
        highest_high = max(high_prices[-stoch_period:])
        lowest_low = min(low_prices[-stoch_period:])
        
        if highest_high == lowest_low:
            stochastic_k = 50
        else:
            stochastic_k = ((current_close - lowest_low) / (highest_high - lowest_low)) * 100
        
        # Calculate RSI
        rsi = calculate_rsi(close_prices, rsi_period)
        
        # Calculate MACD
        macd, signal, histogram = calculate_macd(close_prices)
        
        # Calculate Bollinger Bands
        bb_upper, bb_middle, bb_lower = calculate_bollinger_bands(close_prices)
        
        # Calculate Moving Averages
        ma_5, ma_10, ma_20, ma_50 = calculate_moving_averages(close_prices)
        
        # Calculate additional metrics
        avg_volume = np.mean(volumes[-20:]) if len(volumes) >= 20 else np.mean(volumes)
        current_volume = volumes[-1] if volumes else 0
        volume_ratio = current_volume / avg_volume if avg_volume > 0 else 0
        
        # Price position within Bollinger Bands
        if bb_upper and bb_lower:
            bb_position = ((current_price - bb_lower) / (bb_upper - bb_lower)) * 100
        else:
            bb_position = None
        
        # Trend analysis
        trend_5_20 = "Up" if ma_5 and ma_20 and ma_5 > ma_20 else "Down" if ma_5 and ma_20 else "Neutral"
        trend_20_50 = "Up" if ma_20 and ma_50 and ma_20 > ma_50 else "Down" if ma_20 and ma_50 else "Neutral"
        
        return {
            'Symbol': symbol,
            'Price': current_price,
            'Change': change,
            'Change %': change_percent,
            '1D Change': one_day_change,
            '1D Change %': one_day_change_percent,
            'Stochastic %K': stochastic_k,
            'RSI': rsi,
            'MACD': macd,
            'MACD Signal': signal,
            'MACD Histogram': histogram,
            'BB Upper': bb_upper,
            'BB Middle': bb_middle,
            'BB Lower': bb_lower,
            'BB Position %': bb_position,
            'MA 5': ma_5,
            'MA 10': ma_10,
            'MA 20': ma_20,
            'MA 50': ma_50,
            'Volume': current_volume,
            'Avg Volume': avg_volume,
            'Volume Ratio': volume_ratio,
            'Trend 5/20': trend_5_20,
            'Trend 20/50': trend_20_50,
            'High 52W': meta.get('fiftyTwoWeekHigh', 0),
            'Low 52W': meta.get('fiftyTwoWeekLow', 0),
            'Market Cap': meta.get('marketCap', 0),
            'Updated': datetime.now().strftime("%H:%M:%S")
        }
        
    except Exception as e:
        st.error(f"Error fetching data for {symbol}: {str(e)}")
        return None

def scan_all_stocks(stock_list, filters=None):
    """
    Scan ALL stocks first, then apply filters and sorting
    """
    all_stocks_data = []
    progress_bar = st.progress(0)
    status_text = st.empty()
    
    for i, symbol in enumerate(stock_list):
        status_text.text(f"Scanning {i+1}/{len(stock_list)}: {symbol}")
        
        stock_data = get_comprehensive_stock_data(symbol)
        if stock_data:
            all_stocks_data.append(stock_data)
        
        progress_bar.progress((i + 1) / len(stock_list))
        time.sleep(0.1)  # Rate limiting
    
    progress_bar.empty()
    status_text.empty()
    
    return all_stocks_data

def apply_filters(stock_data, filters):
    """Apply user-defined filters to stock data"""
    try:
        # Only positive change filter
        if filters['positive_only'] and stock_data['Change %'] <= 0:
            return False
        
        # Stochastic filter
        if not (filters['min_stochastic'] <= stock_data['Stochastic %K'] <= filters['max_stochastic']):
            return False
        
        # RSI filter
        if stock_data['RSI'] and not (filters['min_rsi'] <= stock_data['RSI'] <= filters['max_rsi']):
            return False
        
        # Change % filter
        if stock_data['Change %'] < filters['min_change_percent']:
            return False
        
        # Volume filter
        if stock_data['Volume Ratio'] < filters['min_volume_ratio']:
            return False
        
        # Market cap filter
        if stock_data['Market Cap'] < filters['min_market_cap']:
            return False
        
        return True
    except:
        return False

def filter_and_sort_stocks(all_stocks_data, filters, sort_by, ascending, target_count):
    """Filter stocks and sort by selected indicator"""
    # Apply filters
    filtered_stocks = []
    for stock in all_stocks_data:
        if apply_filters(stock, filters):
            filtered_stocks.append(stock)
    
    # Convert to DataFrame for sorting
    if filtered_stocks:
        df = pd.DataFrame(filtered_stocks)
        
        # Sort by selected indicator
        df = df.sort_values(sort_by, ascending=ascending)
        
        # Limit to target count
        df = df.head(target_count)
        
        return df.to_dict('records')
    
    return []

# Sidebar controls
with st.sidebar:
    st.header("Advanced Stock Screener")
    
    # PRIMARY SORT SELECTION (NEW)
    st.subheader("🎯 Primary Sort & Filter")
    sort_by_indicator = st.selectbox(
        "Sort results by:",
        options=['Change %', '1D Change %', 'Stochastic %K', 'RSI', 'Volume Ratio', 'Price', 'MACD'],
        index=0,
        help="Select the primary indicator to sort your results"
    )
    
    sort_ascending = st.checkbox("Sort in ascending order", False)
    
    # Target number of results
    target_results = st.number_input(
        "Number of results to show", 
        min_value=10, 
        max_value=2000, 
        value=200, 
        step=10,
        help="After scanning all stocks, show top N results"
    )
    
    # Only positive change filter
    positive_only = st.checkbox("Show only positive change stocks", True)
    
    # Technical indicator periods
    st.subheader("Indicator Periods")
    stochastic_period = st.number_input("Stochastic %K Period", 5, 30, 14, 1)
    rsi_period = st.number_input("RSI Period", 5, 30, 14, 1)
    
    # Filters
    st.subheader("Additional Filters")
    
    # Stochastic filter
    st.write("**Stochastic %K Filter**")
    min_stochastic = st.slider("Min Stochastic %K", 0.0, 100.0, 0.0, 1.0)
    max_stochastic = st.slider("Max Stochastic %K", 0.0, 100.0, 100.0, 1.0)
    
    # RSI filter
    st.write("**RSI Filter**")
    min_rsi = st.slider("Min RSI", 0.0, 100.0, 0.0, 1.0)
    max_rsi = st.slider("Max RSI", 0.0, 100.0, 100.0, 1.0)
    
    # Other filters
    min_change_percent = st.number_input("Min Change %", -50.0, 50.0, -50.0, 0.1)
    min_volume_ratio = st.number_input("Min Volume Ratio", 0.0, 10.0, 0.0, 0.1)
    min_market_cap = st.number_input("Min Market Cap (₹)", 0, 1000000000000, 0, 1000000000)
    
    # Stock list input
    st.subheader("Stock List")
    use_example = st.checkbox("Use example stocks (20 stocks)", value=True)
    
    if not use_example:
        st.info("Replace EXAMPLE_STOCKS in the code with your 2000 stock list")
        custom_stocks = st.text_area(
            "Enter stock symbols (comma separated)", 
            value=", ".join(EXAMPLE_STOCKS),
            height=100
        )
        stock_list = [s.strip().upper() for s in custom_stocks.split(",") if s.strip()]
    else:
        stock_list = EXAMPLE_STOCKS

# Main dashboard
st.title("🚀 Advanced Stock Screener with Technical Indicators")

# Display current settings
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Sort By", sort_by_indicator)
with col2:
    st.metric("Target Results", target_results)
with col3:
    st.metric("Stochastic Period", stochastic_period)
with col4:
    st.metric("Total Stocks", len(stock_list))

# Create filters dictionary
filters = {
    'positive_only': positive_only,
    'min_stochastic': min_stochastic,
    'max_stochastic': max_stochastic,
    'min_rsi': min_rsi,
    'max_rsi': max_rsi,
    'min_change_percent': min_change_percent,
    'min_volume_ratio': min_volume_ratio,
    'min_market_cap': min_market_cap
}

# Scan button
if st.button("🔍 Scan All Stocks & Sort"):
    with st.spinner("Scanning ALL stocks first..."):
        # Step 1: Scan all stocks
        all_stocks_data = scan_all_stocks(stock_list, filters)
        st.session_state.all_stocks_data = all_stocks_data
        
        if all_stocks_data:
            st.success(f"✅ Scanned {len(all_stocks_data)} stocks successfully!")
            
            # Step 2: Filter and sort
            with st.spinner(f"Filtering and sorting by {sort_by_indicator}..."):
                filtered_sorted_stocks = filter_and_sort_stocks(
                    all_stocks_data, 
                    filters, 
                    sort_by_indicator, 
                    sort_ascending, 
                    target_results
                )
                
                if filtered_sorted_stocks:
                    st.session_state.filtered_stocks = filtered_sorted_stocks
                    st.session_state.last_scan_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    st.success(f"📊 Found {len(filtered_sorted_stocks)} stocks matching criteria, sorted by {sort_by_indicator}!")
                else:
                    st.warning("No stocks found matching the criteria")
        else:
            st.error("Failed to scan stocks. Please check your internet connection.")

# Re-sort button (if data already exists)
if st.session_state.all_stocks_data and st.button("🔄 Re-sort with Current Settings"):
    with st.spinner(f"Re-sorting by {sort_by_indicator}..."):
        filtered_sorted_stocks = filter_and_sort_stocks(
            st.session_state.all_stocks_data, 
            filters, 
            sort_by_indicator, 
            sort_ascending, 
            target_results
        )
        
        if filtered_sorted_stocks:
            st.session_state.filtered_stocks = filtered_sorted_stocks
            st.success(f"📊 Re-sorted {len(filtered_sorted_stocks)} stocks by {sort_by_indicator}!")
        else:
            st.warning("No stocks found matching the current criteria")

# Display results
if st.session_state.filtered_stocks:
    st.subheader(f"📊 Results: {len(st.session_state.filtered_stocks)} Stocks (Sorted by {sort_by_indicator})")
    st.caption(f"Last scan: {st.session_state.last_scan_time}")
    
    # Convert to DataFrame
    df = pd.DataFrame(st.session_state.filtered_stocks)
    
    # Display summary statistics
    st.subheader("📈 Summary Statistics")
    col1, col2, col3, col4, col5 = st.columns(5)
    
    with col1:
        st.metric("Avg Change %", f"{df['Change %'].mean():.2f}%")
    with col2:
        st.metric("Avg 1D Change %", f"{df['1D Change %'].mean():.2f}%")
    with col3:
        st.metric("Avg RSI", f"{df['RSI'].mean():.1f}")
    with col4:
        st.metric("Avg Stochastic %K", f"{df['Stochastic %K'].mean():.1f}")
    with col5:
        st.metric("Avg Volume Ratio", f"{df['Volume Ratio'].mean():.2f}")
    
    # Show scan summary
    if st.session_state.all_stocks_data:
        total_scanned = len(st.session_state.all_stocks_data)
        positive_count = len([s for s in st.session_state.all_stocks_data if s['Change %'] > 0])
        
        st.info(f"📊 Scan Summary: {total_scanned} stocks scanned, {positive_count} with positive change, {len(st.session_state.filtered_stocks)} matching all filters")
    
    # Display selection options
    st.subheader("📋 Display Options")
    display_columns = st.multiselect(
        "Select columns to display",
        options=df.columns.tolist(),
        default=['Symbol', 'Price', 'Change %', '1D Change %', 'Stochastic %K', 'RSI', 'MACD', 'Volume Ratio', 'Trend 5/20']
    )
    
    # Filter and display dataframe
    if display_columns:
        display_df = df[display_columns].copy()
        
        # Display the main table
        st.dataframe(
            display_df.style.format({
                'Price': '{:.2f}',
                'Change': '{:.2f}',
                'Change %': '{:.2f}%',
                '1D Change': '{:.2f}',
                '1D Change %': '{:.2f}%',
                'Stochastic %K': '{:.1f}',
                'RSI': '{:.1f}',
                'MACD': '{:.4f}',
                'MACD Signal': '{:.4f}',
                'MACD Histogram': '{:.4f}',
                'BB Upper': '{:.2f}',
                'BB Middle': '{:.2f}',
                'BB Lower': '{:.2f}',
                'BB Position %': '{:.1f}%',
                'MA 5': '{:.2f}',
                'MA 10': '{:.2f}',
                'MA 20': '{:.2f}',
                'MA 50': '{:.2f}',
                'Volume': '{:,}',
                'Avg Volume': '{:,}',
                'Volume Ratio': '{:.2f}',
                'High 52W': '{:.2f}',
                'Low 52W': '{:.2f}',
                'Market Cap': '{:,}'
            }).map(
                lambda x: 'color: green' if isinstance(x, (int, float)) and x >= 0 
                else 'color: red' if isinstance(x, (int, float)) and x < 0 
                else '', 
                subset=[col for col in ['Change', 'Change %', '1D Change', '1D Change %'] if col in display_columns]
            ).background_gradient(
                subset=[col for col in ['RSI', 'Stochastic %K'] if col in display_columns], 
                cmap='RdYlGn', 
                vmin=0, 
                vmax=100
            ),
            use_container_width=True,
            height=600
        )
    
    # Export functionality
    st.subheader("💾 Export Results")
    
    # CSV export
    csv = df.to_csv(index=False)
    st.download_button(
        label="📥 Download Results (CSV)",
        data=csv,
        file_name=f"stocks_sorted_by_{sort_by_indicator.replace(' ', '_').replace('%', 'pct')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
        mime="text/csv"
    )
    
    # Display top performers in different categories
    st.subheader("🏆 Top Performers (from filtered results)")
    
    tab1, tab2, tab3, tab4 = st.tabs(["📈 Best Change %", "📊 Best 1D Change %", "🎯 Best RSI", "⚡ High Volume"])
    
    with tab1:
        top_change = df.nlargest(10, 'Change %')[['Symbol', 'Change %', 'Price', 'RSI', 'Stochastic %K']]
        st.dataframe(
            top_change.style.format({
                'Change %': '{:.2f}%',
                'Price': '{:.2f}',
                'RSI': '{:.1f}',
                'Stochastic %K': '{:.1f}'
            }).background_gradient(subset=['Change %'], cmap='Greens'),
            use_container_width=True
        )
    
    with tab2:
        top_1d_change = df.nlargest(10, '1D Change %')[['Symbol', '1D Change %', 'Price', 'RSI', 'Volume Ratio']]
        st.dataframe(
            top_1d_change.style.format({
                '1D Change %': '{:.2f}%',
                'Price': '{:.2f}',
                'RSI': '{:.1f}',
                'Volume Ratio': '{:.2f}'
            }).background_gradient(subset=['1D Change %'], cmap='Greens'),
            use_container_width=True
        )
    
    with tab3:
        # Show stocks with RSI in optimal range (30-70)
        optimal_rsi = df[(df['RSI'] >= 30) & (df['RSI'] <= 70)].nlargest(10, 'Change %')[['Symbol', 'RSI', 'Change %', 'Stochastic %K', 'Price']]
        st.dataframe(
            optimal_rsi.style.format({
                'RSI': '{:.1f}',
                'Change %': '{:.2f}%',
                'Stochastic %K': '{:.1f}',
                'Price': '{:.2f}'
            }).background_gradient(subset=['RSI'], cmap='RdYlGn', vmin=0, vmax=100),
            use_container_width=True
        )
    
    with tab4:
        top_volume = df.nlargest(10, 'Volume Ratio')[['Symbol', 'Volume Ratio', 'Volume', 'Change %', 'Price']]
        st.dataframe(
            top_volume.style.format({
                'Volume Ratio': '{:.2f}',
                'Volume': '{:,}',
                'Change %': '{:.2f}%',
                'Price': '{:.2f}'
            }).background_gradient(subset=['Volume Ratio'], cmap='Blues'),
            use_container_width=True
        )

else:
    st.info("👆 Click 'Scan All Stocks & Sort' to analyze all stocks and get sorted results by your chosen indicator")
    
    # Show what's new
    st.subheader("🆕 Scanning")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.write("** Scanning Process:**")
        st.write("- Scans ALL stocks first")
        st.write("- Then applies filters and sorting")
        st.write("- Choose primary sort indicator upfront")
        st.write("- Re-sort option without re-scanning")
        
    with col2:
        st.write("**🎯 Enhanced Features:**")
        st.write("- Sort by any indicator before scanning")
        st.write("- Scan summary statistics")
        st.write("- Better progress tracking")
        st.write("- Option for positive-only stocks")

# Information about the process
with st.expander("🔄 How the New Process Works"):
    st.write("""
    **Step 1: Choose Your Primary Indicator**
    - Select what you want to sort by (Stochastic %K, 1D Change %, etc.)
    - Choose ascending or descending order
    - Set number of results to show
    
    **Step 2: Scan All Stocks**
    - Process every stock in your list
    - Calculate all technical indicators
    - No early stopping - complete analysis
    
    **Step 3: Filter & Sort**
    - Apply your filters (RSI, Stochastic, etc.)
    - Sort by your chosen indicator
    - Show top N results
    
    **Step 4: Re-sort Anytime**
    - Change settings and re-sort without re-scanning
    - Instant results from cached data
    """)

# Instructions for full implementation
st.subheader("🔧 Key Feature")
st.write("""
**Major Key Feature:**

1. **Complete Scanning**: It scans ALL stocks first, then sorts
2. **Primary Sort Selection**: Choose your sort indicator before scanning
3. **Two-Step Process**: Scan once, sort multiple times
4. **Better Progress**: See total scanned vs filtered results
5. **Re-sort Feature**: Change settings without re-scanning

**Usage:**
1. Choose your primary sort indicator (Stochastic %K, 1D Change %, etc.)
2. Set filters and target result count
3. Click "Scan All Stocks & Sort"
4. Use "Re-sort" to try different settings quickly
""")